### PR TITLE
New logo link added to README

### PR DESCRIPTION
**Pull request by 100mik**
Link to new logo added to README.
I would be happy to send you the source file or variations.
Cheers!

Do let me know what you think about it!

In response to issue #11

### CODE REVIEW

**Comment by 100mik** [comment]
Made slight tweaks to make it look better.

**Comment by gilsonmandalogo** [comment]
@100mik Thank you!
Looks very nice. You can send the source file or variation to my personal email (it is public on my Github profile).
Cheers!

**Comment by 100mik** [comment]
Alright! I will mail it. 

Can you please add "hacktoberfest" as a repository topic so that my contribution is taken into account?
As mentioned here: https://github.com/digitalocean/hacktoberfest/pull/596

**Comment by gilsonmandalogo** [comment]
@100mik Sorry, I din't know that. Added "hacktoberfest" topic to this repo.

**Pull request merged**
